package nl.goedkoopschappen.goedkoopschappen.models;

public enum ProductType {

    /** This enums follows Albert Heijn's categorization of their products.

    TODO: LOOK INTO MAKING SEPARATE ONE PER SUPPLIER*/

    AARDAPPEL_GROENTEN_FRUIT, VERSE_KANT_EN_KLAAR_MAALTIJDEN_SALADES, VLEES_KIP_VIS_VEGA,
    KAAS_VLEESWAREN_DELICATESSEN, ZUIVEL_EIEREN, BAKKERIJ, ONTBIJTGRANEN_BROODBELEG_TUSSENDOOR,
    FRISDRANKEN_SAPPEN_KOFFIE_THEE, WIJN, BIER_STERKEDRANK_APERITIEVEN,
    PASTA_RIJST_INTERNATIONALEKEUKEN, SOEPEN_CONSERVEREN_SAUZEN_SMAAKMAKERS, SNOEP_KOEK_CHIPS,
    DIEPVRIES, DROGISTERIJ_BABY, BEWUSTE_VOEDING, HUISHOUDEN_HUISDIER, KOKEN_TAFELEN_NONFOOD

}